import Providers from './providers'
import './global.css'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import {ThemeProvider} from 'next-themes'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <UserProvider>
        <body>
            <ThemeProvider attribute='class'>
              <Providers>{children}</Providers>  
            </ThemeProvider>
          
        </body>
      </UserProvider>
    </html>
  )
}